---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extensions.gardener.cloud:extension-shoot-cert-service:shoot
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - "extensions"
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - update
  - watch
  - create
  - delete
- apiGroups:
  - cert.gardener.cloud
  resources:
  - certificates
  - certificates/status
  verbs:
  - get
  - list
  - update
  - watch
  - create
  - delete
{{- if .Values.dnsChallengeOnShoot.enabled }}
- apiGroups:
  - dns.gardener.cloud
  resources:
  - dnsentries
  verbs:
  - get
  - list
  - update
  - watch
  - create
  - delete
{{- end}}
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - update
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: extensions.gardener.cloud:extension-shoot-cert-service:shoot
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: extensions.gardener.cloud:extension-shoot-cert-service:shoot
subjects:
- kind: User
  name: {{ .Values.shootUserName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: extensions.gardener.cloud:extension-shoot-cert-service:shoot
  namespace: kube-system
  labels:
    app.kubernetes.io/name: gardener-extension-shoot-cert-service
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - cluster-identity
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: extensions.gardener.cloud:extension-shoot-cert-service:shoot
  namespace: kube-system
  labels:
    app.kubernetes.io/name: {{ include "cert-management.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extensions.gardener.cloud:extension-shoot-cert-service:shoot
subjects:
  - kind: User
    name: {{ .Values.shootUserName }}
